# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='tarket',
            new_name='target',
        ),
    ]
