# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180129_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
