# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180112_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='company_image',
        ),
    ]
