# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180129_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='hr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
