# Generated by Django 2.0.1 on 2018-03-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_companyinfo_hr_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disabilityinfo',
            old_name='address',
            new_name='current_address',
        ),
        migrations.RemoveField(
            model_name='disabilityinfo',
            name='get_more_info',
        ),
        migrations.RemoveField(
            model_name='disabilityinfo',
            name='job_interest',
        ),
        migrations.RemoveField(
            model_name='disabilityinfo',
            name='more_resume',
        ),
        migrations.RemoveField(
            model_name='disabilityinfo',
            name='province',
        ),
        migrations.RemoveField(
            model_name='disabilityinfo',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='disabilityinfo',
            name='talent2',
        ),
        migrations.RemoveField(
            model_name='disabilityinfo',
            name='talent3',
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='birth_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='branch',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='current_province',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='current_status',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='disability_reason',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='disable_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='disabled_equiptment',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='disabled_year',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='educational_institution',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='expected_salary3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='faculty',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='graduate',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='graduate_year',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='helping_myself',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='job_interest1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='job_interest2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='language',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='last_company_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='last_company_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='listen_skill',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='position',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='quit_job_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='reading_skill',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='region',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='registration_address',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='registration_province',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='speaking_skill',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='traveling_by_myself',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='work_in_other_province',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='working_end_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='working_start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='working_time',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='writeing_skill',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='job_exp',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
