# Generated by Django 2.0.1 on 2018-03-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180304_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disabilityinfo',
            old_name='writeing_skill',
            new_name='level_computer_skill1',
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='computer_skill1',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='computer_skill2',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='computer_skill3',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='computer_skill4',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='computer_skill5',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='level_computer_skill2',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='level_computer_skill3',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='level_computer_skill4',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='level_computer_skill5',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='writing_skill',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=50, null=True),
        ),
    ]
