# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_merge_20180115_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
