# Generated by Django 2.0.1 on 2018-03-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180304_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabilityinfo',
            name='congenital_disease',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='lawsuit',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=10, null=True),
        ),
    ]
