# Generated by Django 2.0.1 on 2018-03-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_disabilityinfo_job_interest3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='listen_skill',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='disability_level',
        ),
        migrations.RemoveField(
            model_name='job',
            name='reading_skill',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='speaking_skill',
        ),
        migrations.RemoveField(
            model_name='job',
            name='writing_skill',
        ),
        migrations.AddField(
            model_name='job',
            name='disabled_welfare',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='history_of_education',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
