# Generated by Django 2.0.1 on 2018-03-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180307_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=250, null=True),
        ),
    ]
