# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180122_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qulification',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='traveling',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='job',
            name='welfare',
            field=models.CharField(max_length=5000),
        ),
    ]
