# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_notifications'),
        ('myapp', '0013_auto_20180122_1218'),
    ]

    operations = [
    ]
