# Generated by Django 2.0.1 on 2018-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_job_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabilityinfo',
            name='expected_salary1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='expected_salary2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='expected_salary3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
