# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20180122_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disabilityinfo',
            name='expected_salary',
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='expected_salary1',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='expected_salary2',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
