# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_merge_20180122_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
