# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_notifications'),
        ('myapp', '0014_auto_20180122_2252'),
    ]

    operations = [
    ]
