# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_merge_20180123_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabilityinfo',
            name='province',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='province',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='message',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='expected_salary1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='expected_salary2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
