# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_notifications_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='obj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
