# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_notifications_obj'),
        ('myapp', '0016_auto_20180123_1016'),
    ]

    operations = [
    ]
