# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_notifications_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmCompany',
            new_name='statusDisability',
        ),
        migrations.RenameModel(
            old_name='ConfirmJob',
            new_name='statusJob',
        ),
    ]
