# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20180124_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdisability',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='statusjob',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
