# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20180124_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdisability',
            name='status',
            field=models.CharField(choices=[('ยังไม่ส่งคำเชิญ', 'ยังไม่ส่งคำเชิญ'), ('ส่งคำเชิญ', 'ส่งคำเชิญ'), ('ตอบรับคำเชิญ', 'ตอบรับคำเชิญ')], default='RED', max_length=5),
        ),
    ]
