# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_job_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phone_no',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
