# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_job_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default='ไม่ระบุ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='info',
            field=models.CharField(default='ไม่ระบุ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone_no',
            field=models.CharField(default='ไม่ระบุ', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='website',
            field=models.CharField(default='ไม่ระบุ', max_length=50),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='address',
            field=models.CharField(blank=True, default='ไม่ระบุ', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='phone_no',
            field=models.CharField(default='ไม่ระบุ', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='detail',
            field=models.CharField(default='ไม่ระบุ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone_no',
            field=models.CharField(default='ไม่ระบุ', max_length=20),
        ),
    ]
