# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20180127_1714'),
        ('myapp', '0033_auto_20180127_0035'),
    ]

    operations = [
    ]
