# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 11:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_merge_20180127_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
