# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_job_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='detail',
        ),
    ]
