# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_auto_20180127_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='welfare',
        ),
    ]
