# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(default='-', max_length=20)),
                ('address', models.CharField(default='-', max_length=1000)),
                ('info', models.CharField(default='-', max_length=1000)),
                ('website', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=30)),
                ('company_type', models.CharField(max_length=100)),
                ('more_resume', models.FileField(default='', upload_to='resume/')),
                ('get_more_info', models.BooleanField()),
                ('company_image', models.ImageField(default='', upload_to='companyPicture/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
