# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='more_resume',
        ),
    ]
