# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_remove_company_more_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(default='-', max_length=20)),
                ('address', models.CharField(default='-', max_length=1000)),
                ('info', models.CharField(default='-', max_length=1000)),
                ('website', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=30)),
                ('company_type', models.CharField(max_length=100)),
                ('get_more_info', models.BooleanField()),
                ('company_image', models.ImageField(default='', upload_to='companyPicture/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(default='-', max_length=20)),
                ('address', models.CharField(blank=True, default='-', max_length=1000, null=True)),
                ('disability_cate', models.CharField(max_length=100)),
                ('lastest_job', models.CharField(max_length=100)),
                ('lastest_office', models.CharField(max_length=100)),
                ('expected_salary', models.CharField(max_length=50)),
                ('expected_welfare', models.CharField(max_length=500)),
                ('talent', models.CharField(max_length=300)),
                ('talent2', models.CharField(max_length=300)),
                ('talent3', models.CharField(max_length=300)),
                ('more_resume', models.FileField(default='', upload_to='resume/')),
                ('get_more_info', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disability_cate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expected_welfare',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='get_more_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastest_job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastest_office',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='more_resume',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='talent2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='talent3',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Profile'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Profile'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
