# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_companyinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_th', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('detail', models.CharField(default='', max_length=2000)),
                ('disability_cate', models.CharField(max_length=100)),
                ('traveling', models.CharField(max_length=1000)),
                ('welfare', models.CharField(max_length=1000)),
                ('salary', models.CharField(max_length=50)),
                ('company_image', models.ImageField(default='', upload_to='createJob/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.CompanyInfo')),
            ],
        ),
    ]
