# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_contact'),
        ('myapp', '0007_job'),
    ]

    operations = [
    ]
