# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180115_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disabilityinfo',
            old_name='lastest_job',
            new_name='job_interest',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default='-', max_length=5000),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='info',
            field=models.CharField(default='-', max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='address',
            field=models.CharField(blank=True, default='-', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='detail',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
