# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180121_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disabilityinfo',
            name='lastest_office',
        ),
        migrations.AddField(
            model_name='disabilityinfo',
            name='job_exp',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='expected_welfare',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='more_resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='talent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='talent2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='disabilityinfo',
            name='talent3',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
