# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180121_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='age',
            new_name='age1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='age2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
