# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_confirmcompany_confirmjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmjob',
            name='company',
        ),
        migrations.AddField(
            model_name='confirmjob',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Job'),
        ),
    ]
