# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_statusdisability_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ยังไม่ส่งคำเชิญ', 'ยังไม่ส่งคำเชิญ'), ('ส่งคำเชิญ', 'ส่งคำเชิญ'), ('ตอบรับคำเชิญ', 'ตอบรับคำเชิญ'), ('สมัคร', 'สมัคร')], max_length=5)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.CompanyInfo')),
                ('disability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.DisabilityInfo')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Job')),
            ],
        ),
        migrations.RemoveField(
            model_name='statusdisability',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='statusdisability',
            name='job',
        ),
        migrations.RemoveField(
            model_name='statusdisability',
            name='user',
        ),
        migrations.RemoveField(
            model_name='statusjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='statusjob',
            name='user',
        ),
        migrations.DeleteModel(
            name='statusDisability',
        ),
        migrations.DeleteModel(
            name='statusJob',
        ),
    ]
