# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20180124_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteprocess',
            name='company',
        ),
    ]
