# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_inviteprocess_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteprocess',
            name='status',
            field=models.CharField(choices=[('ยังไม่ส่งคำเชิญ', 'ยังไม่ส่งคำเชิญ'), ('ส่งคำเชิญ', 'ส่งคำเชิญ'), ('ตอบรับคำเชิญ', 'ตอบรับคำเชิญ')], max_length=20),
        ),
    ]
