# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_merge_20180124_1353'),
        ('myapp', '0029_auto_20180125_0035'),
    ]

    operations = [
    ]
