# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20180125_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
