# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_inviteprocess_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
