# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_inviteprocess_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='obj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
