# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 12:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_remove_job_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='content',
            new_name='detail',
        ),
        migrations.AlterField(
            model_name='job',
            name='welfare',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
